# Here you can specify default options for TinyMCE across all controllers
#
 theme: advanced
 plugins:
  - table
  - fullscreen
 theme_advanced_buttons3_add: tablecontrols
 theme_advanced_toolbar_location: top

